apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: React-App
  annotations:
    github.com/project-slug: ballakeita/React-App
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: automation
